<!--suppress ALL -->
<div class="title-block">
    <h3 class="title"> Edit <span class="sparkline bar" data-type="bar">Category</span> </h3>
</div>
<div class="card card-block" id="submit-category" v-cloak >
    <form method="POST">
        <div class="alert " v-if="Message" v-bind:class="HasError ? 'alert-danger' : 'alert-success' " >
            <a id="my-close" href="#" class="close" data-dismiss="alert" aria-label="close">X</a>
            {{Message}}
        </div>

        <div class="form-group" v-bind:class=" errors.name ? 'has-error' : '' ">
            <label class="control-label" v-bind:class=" errors.name ? 'text-danger' : 'text-success' " for="categoryName">Category Name:</label>
            <input type="text" class="form-control underlined" name="name" placeholder="Name of category" id="categoryName" v-model="editCategory.name">

            <span class="has-error" v-if="errors.name">{{ errors.name }}</span>
        </div>

        <div class="form-group">
            <label class="control-label" for="url">Change parent category:</label>
            <v-select :options="categories"  v-model="parent" class="control-label"></v-select>
        </div>

        <div class="col-sm-4 push-sm-4">
            <button type="submit" @click.prevent="updateCategory" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
<script>
    Vue.component('v-select', VueSelect.VueSelect);
    var parent_data = '<?= $parent_data ?>';
    if(!parent_data){
        parent_data = '';
    }
    new Vue({
        el: '#submit-category',
        data:{
            categories: JSON.parse('<?= $allCategories ?>'),
            parent: JSON.parse(parent_data),
            editCategory: JSON.parse('<?= $category_data ?>'),
            errors: [],
        },
        props: [
            'HasError',
            'Message',
        ],

        methods: {
            updateCategory: function () {

                var category = {
                    parent_id: this.parent.value,
                    name: this.editCategory.name,
                    id : this.editCategory.id
                };
                this.$http.post('/admin/categories/updateCategory', category, {}).then((response) => {
                    if(response.data.error == true) {
                        this.HasError = true;
                        this.errors = response.data.errors;
                        this.Message  = response.data.message;
                    } else{
                        this.errors = [];
                        this.HasError = false;
                        this.Message = response.data.message;
                    }
                });
            }
        }
    })
</script>