<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<title> Interno CMS system </title>
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="apple-touch-icon" href="apple-touch-icon.png">
<!-- Place favicon.ico in the root directory -->
<?php
    echo \Phalcon\Tag::stylesheetLink("/backend/css/vendor.css");
    echo \Phalcon\Tag::stylesheetLink("/backend/css/app-green.css");
    echo \Phalcon\Tag::stylesheetLink("/backend/css/custom.css");

    echo \Phalcon\Tag::javascriptInclude("/backend/js/vue.js");
    echo \Phalcon\Tag::javascriptInclude("/backend/js/vue-resource.min.js");
    echo \Phalcon\Tag::javascriptInclude("/backend/js/vue-select.js");
//    echo \Phalcon\Tag::javascriptInclude("/backend/dist/app.js");
?>